### ISSUE TITLE
关于webssh

### ISSUE THREAD

**Issue by xiamujun** [hequan2017/chain#2]
[简述你的问题]
请教下基于web的ssh终端是怎么嵌入https://github.com/huashengdun/webssh实现登录的？
尝试部署了webssh，看webssh登录是通过form的方式将host，port等信息提交的；想问下您是通过什么方式post数据到webssh的，谢谢。

**Comment by hequan2017** [comment]
我是通过AJAX的方式 提交 账号 密码 或者密钥 post 给 webssh的。

这个其中涉及到跨域了。我把 webssh中的 验证csrf取消了。所以别的系统post数据  使用无问题。

具体使用，可以参考我的项目。还涉及到密码加密解密。

**Comment by xiamujun** [comment]
好的，非常感谢。
